version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
  - package-ecosystem: "npm"
    directory: "./backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
  - package-ecosystem: "npm"
    directory: "./frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
