apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-pvc
  namespace: bookcars
spec:
  accessModes:
    - ReadWriteOnce # Changed from ReadWriteMany since vultr-block-storage doesn't support it
  storageClassName: vultr-block-storage # Using your default storage class
  resources:
    requests:
      storage: 20Gi
