name: containerize

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: environment for the container image
        options:
          - development
          - staging
          - production
        default: development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [frontend, backend, admin]

    env:
      REPO_PREFIX: ghcr.io/${{ github.repository }}/${{ github.event.inputs.name || 'development' }}/${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: create-env-files
        run: |
          cp ${{ matrix.component }}/.env.docker.example ${{ matrix.component }}/.env.docker

      # Uncomment this block if we want to push to GHCR
      # - name: login-ghcr
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build-docker-image
        run: |
          REPO_PREFIX_LOWER=$(echo "$REPO_PREFIX" | tr '[:upper:]' '[:lower:]')
          docker build -t $REPO_PREFIX_LOWER:${{ github.sha }} -f ${{ matrix.component }}/Dockerfile .
          
          # Uncomment these lines if we want to push images to GHCR
          # docker push $REPO_PREFIX_LOWER:${{ github.sha }}
          # docker tag $REPO_PREFIX_LOWER:${{ github.sha }} $REPO_PREFIX_LOWER:latest
          # docker push $REPO_PREFIX_LOWER:latest
