name: Update Mobile App URL

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-latest-release-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Determine TAG_NAME
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            echo "Fetching latest release tag from GitHub API..."
            TAG_NAME=$(curl -s https://api.github.com/repos/aelassas/bookcars/releases/latest | jq -r '.tag_name')
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Update .github/latest-release.json
        run: |
          echo "{\"latestApkUrl\": \"https://github.com/aelassas/bookcars/releases/download/${TAG_NAME}/bookcars-${VERSION}.apk\"}" > .github/latest-release.json

      - name: Commit and push latest-release.json
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .github/latest-release.json
          git diff --cached --quiet || git commit -m "chore: update latest-release.json for ${TAG_NAME}"
          git push
